### ISSUE TITLE
TUCAN vs. CSD API problem with 'pairwise' from 'itertools'

### ISSUE THREAD

**Issue by schatzsc** [TUCAN-nest/TUCAN#104]
When trying to import the different TUCAN modules the following ones fail with the an error message:

>>> import **tucan.test_utils**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/test_utils.py", line 3, in <module>
    from tucan.canonicalization import canonicalize_molecule
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/canonicalization.py", line 4, in <module>
    from itertools import pairwise
ImportError: cannot import name 'pairwise' from 'itertools' (unknown location)

With nearly the same error failing are:

**tucan.canonicalization**

Additional problem upon import of tucan.io

**>>> from tucan.io import graph_from_file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/io/__init__.py", line 3, in <module>
    from tucan.io.molfile_reader import (
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/io/molfile_reader.py", line 4, in <module>
    from tucan.io.molfile_v2000_reader import graph_props_from_molfile_v2000
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/io/molfile_v2000_reader.py", line 55
    match _to_int(s):
          ^
SyntaxError: invalid syntax**

Ok are:

**tucan.element_properties**
**tucan.test_utils**
**tucan.visualization**
**tucan.serialization**
**tucan.graph_utils**
**tucan.parser**

**Comment by JanCBrammer** [comment]
The issue is caused by the fact that the CSD Python API is incompatible with Python versions > 3.9.

In the TUCAN codebase we're using Python features that have been introduced in version 3.10:
- the `match case` statement (https://peps.python.org/pep-0634/),
- and `itertools.pairwise` (https://docs.python.org/3/library/itertools.html#itertools.pairwise).

I've contacted the [CSD team](https://downloads.ccdc.cam.ac.uk/documentation/API/), asking if they have plans to support Python > 3.9.
They informed me that "unfortunately there is no current plan to support Python 3.10".

Consequently, I removed  the use of `itertools.pairwise` (a440f81b1e933bef3e84ea6db5565216de210a25)
and `match case` (3866462a2d8ebc226995b0b8140516e6d0aa037f) from TUCAN,
and we should now be compatible with the CSD Python API.
