### ISSUE TITLE
TypeError with Python 3.9

### ISSUE THREAD

**Issue by schatzsc** [TUCAN-nest/TUCAN#108]
The CSD Python API currently only supports Python up to version 3.9: [https://downloads.ccdc.cam.ac.uk/documentation/API/installation_notes.html#python-versions](url)

However, when I install TUCAN as indicated on GitHub and then try to import the library I get an error for all sub-packages other than `tucan.visualization`

One example here:

```
(base) xyz@TUCANs-nest:~$ python3
Python 3.9.13 (main, Aug 25 2022, 23:26:10)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tucan.visualization
>>> import tucan.test_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/test_utils.py", line 3, in <module>
    from tucan.canonicalization import canonicalize_molecule
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/canonicalization.py", line 1, in <module>
    from tucan.graph_utils import attribute_sequence
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/graph_utils.py", line 61, in <module>
    ) -> tuple[str | int | float, ...]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

Most of them seem to trace back to the same error in `tucan.graph_utils` with the exception of `tucan.element_attributes` which produces:

`>>> import tucan.element_attributes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schatzsc/anaconda3/lib/python3.9/site-packages/tucan/element_attributes.py", line 376, in <module>
    ELEMENT_ATTRS: Final[dict[str, dict[str, str | int]]] = {
TypeError: unsupported operand type(s) for |: 'type' and 'type'`

**Comment by JanCBrammer** [comment]
See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#annotation-issues-at-runtime,
specifically https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-x-y-syntax-for-unions.

Fixed with 37e618428e936791b80d0d2e2cb577334d31bf29.
